### ISSUE TITLE
Can't use DeviceConnect iOS SDK in the form of CocoaPods framework.

### ISSUE THREAD

**Issue by kunichiko** [DeviceConnect/DeviceConnect-iOS#159]
I created a sample iOS app using DeviceConnect iOS SDK below:
- https://github.com/kunichiko/DeviceConnect-TestApp-iOS

This app is written in Swift, and links `Device Connect iOS SDK` and `Host plugin` in the form of CocoaPods framework.

The Podfile is like below:
```
swift_version = '3.0' 
use_frameworks!

target 'DCTestApp' do
  pod 'DeviceConnectSDK'
  pod 'DeviceConnectHostPlugin'
end
```
It uses the Pod Spects in the DeviceConnect Spec Repo (https://github.com/DeviceConnect/DeviceConnect-PodSpecs).

## Problem
The app crashed when the SDK opened local OAuth authorization window because the SDK couldn't load the storyboard resource.

I figured out the reason is that the SDK was linked in the framework form, and the `DCBundle()` macro returns nil.

I forked this repository and change the `DCBundle()` macro like below:

### Before
DConnectConst.h
```
#define DCBundle() \
[NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"DConnectSDK_resources" ofType:@"bundle"]]
```

### After
DConnectConst.h
```
NSBundle* DCBundle();
```
DConnectConst.m - new
```
NSBundle* DCBundle() {
    NSBundle* bundle;
    
    bundle = [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:@"DConnectSDK_resources" ofType:@"bundle"]];
    if( bundle ) {
        return bundle;
    }
    bundle = [NSBundle bundleWithPath:[[NSBundle bundleForClass:NSClassFromString(@"DConnectManager")]
                                       pathForResource:@"DConnectSDK_resources" ofType:@"bundle"]];
    return bundle;
}
```

After it failed to load the DeviceConnect SDK's bundle (DConnectSDK_resources.bundle) from main bundle, it will try to load the resource bundle from the DConnectSDK.framework .
(See my commit: https://github.com/kunichiko/DeviceConnect-iOS/commit/864660695e8094901901237c8b776fe442f0c703)

## My suggestion
If the solution above is right to use the SDK with Swift, I will create a pull request for you.
If not, would you show the right solution?

（プロジェクトのルールがわからなかったので念のため英語で書かせていただきましたが、日本語でも対応可能です）

**Comment by Onuzimoyr** [comment]
@kunichiko ご連絡ありがとうございます。現時点では、明確なルール付けなどされておりません。
お問合せの際には、英語でも日本語でも結構です。

@TakayukiHoshi1984 すみませんが、一度ご確認頂くことは可能でしょうか？

**Comment by TakayukiHoshi1984** [comment]
@kunichiko @Onuzimoyr はい、確認いたします。

**Comment by kunichiko** [comment]
承知致しました。どうぞよろしくお願いいたします。

なお、私の案は、以前の実装と挙動がなるべく合うようにするため一度 main bundleからのロードを試みていますが、「"DConnectManager"クラスと同じバンドルからリソースバンドルをロードすれば良い」ということでしたら、以下のようにしてしまっても良いと思います。

```
#define DCBundle() \
[NSBundle bundleWithPath:[[NSBundle bundleForClass:NSClassFromString(@"DConnectManager")]
                                       pathForResource:@"DConnectSDK_resources" ofType:@"bundle"]]
```
※ バンドルを動的に見つけるために、SDK内の代表的なクラスとして DConnectManagerを選びましたが、それ以外を使っても大丈夫です。

ご検討のほど、どうぞよろしくお願いいたします。

**Comment by TakayukiHoshi1984** [comment]
下記マクロで動作確認を行い、LocalOAuthの認証ダイアログが問題なく表示できることを確認できました。

```
#define DCBundle() \
[NSBundle bundleWithPath:[[NSBundle bundleForClass:NSClassFromString(@"DConnectManager")]
                                       pathForResource:@"DConnectSDK_resources" ofType:@"bundle"]]
```
その場合、下記パターンで動作することについて確認しました。
* [DeviceConnect-TestApp-iOS](https://github.com/kunichiko/DeviceConnect-TestApp-iOS)上で認証ダイアログが表示されること。
* 直接修正したDConnectSDKをdConnectBrowserForIOS9に組み込み、そのアプリ上で認証ダイアログが表示されること。

@kunichiko 
お手数ですが、DeviceConnect-iOSのPull Requestの方をお願いしてよろしいですか？

**Comment by kunichiko** [comment]
承知しました!

**Comment by TakayukiHoshi1984** [comment]
#160 
確認できましたので、マージしました。

@kunichiko @Onuzimoyr 
問題がなければ、こちらのISSUEをクローズしようと思います。

**Comment by kunichiko** [comment]
ありがとうございます。問題ありませんのでクローズしてくださいませ。
