### ISSUE TITLE
README.md に日本語が混じっている

### ISSUE THREAD

**Issue by tanjo** [DeviceConnect/DeviceConnect-iOS#24]
以下の箇所が日本語のままになっています

[DeviceConnect iOS について](https://github.com/DeviceConnect/DeviceConnect-iOS#deviceconnect-ios-%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

**Comment by ykkn** [comment]
ご指摘ありがとうございます。修正させていただきました。
